name: Test Bash Script

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash Script
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          mkdir example-project
          mv init.sh example-project/init.sh
          cd example-project
          chmod +x ./init.sh
          ./init.sh "TestApp" "TestNamespace" "$BRANCH_NAME" "12345" "23456" "34567" "45678"
