name: Test & lint JS codebase

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'src/package.json'
      - 'src/package.lock'

permissions: {}

jobs:
  test-and-lint-js:
    name: Test & lint JS codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      # renovate: datasource=node-version depName=node
      NODE_VERSION: 24.12.0

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 # https://github.com/actions/checkout

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0 # https://github.com/actions/cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package.lock') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0 # https://github.com/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        working-directory: src
        run: npm install

      - name: Run JS linter
        working-directory: src
        run: npm run lint
