name: Test Bash Script

on: [push, pull_request]

jobs:
  test:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash Script
        run: |
          mkdir example-project
          mv init.sh example-project/init.sh
          cd example-project
          chmod +x ./init.sh
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ./init.sh "TestApp" "TestNamespace" "$BRANCH_NAME" "12345" "23456" "34567" "45678"
